services:
  setup:
    image: pipeline:latest
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./data:/app/data
    networks:
      - pipeline_network
    restart: "no"

  etl:
    image: pipeline:latest
    depends_on:
      - setup
    command: >
      python src/ingestion/ingest_cnpj.py && \
      python src/processing/processing_silver.py && \
      python src/processing/processing_gold.py
    volumes:
      - ./data:/app/data
    env_file:
      - .env
    networks:
      - pipeline_network

networks:
  pipeline_network:
    driver: bridge